### ISSUE TITLE
推荐 Good Prose with Grace 课程的英语阅读材料

### ISSUE THREAD

**Issue by megtog** [IntensiveCoLearning/english#3]
从 [Good Prose with Grace 课程介绍（公众号文章）][wechat] 复制来的一份阅读材料

[wechat]: https://mp.weixin.qq.com/s?src=11&timestamp=1718346854&ver=5321&signature=N6dxUOnLQdMjM1BatmgA*mkE6duC2Hni6rPB9CcHeVWI*4VpNl5Jej5un2Q4aNLXw0tTs1Z82UDzehWu9OkT0oy21cdgHAjki4JpAL9EKSIdKuOU2de-cg-YxeTC8BqF

### Good Prose with Grace: An Intermediate English Reading Class

In this five-week course, students will expand their English vocabularies and learn to recognize good English prose while becoming active readers. The class will draw upon the “practical criticism” style of close reading taught in the English department at the University of Cambridge. In practical criticism, we begin with the words on the page, and focus first on questions of language, form and meaning before considering the text’s wider historical and cultural contexts. The reading list consists of short essays and articles by some of the most enduring and influential writers of the 20th century. 

#### Week 1: English as a Second Language

Amy Tan, “Mother Tongue”

Optional reading: Eric Liu, “Notes of a Native Speaker”

#### Week 2: How to Write

George Orwell, “Politics and the English Language”

Optional reading: George Orwell, “Shooting an Elephant”

#### Week 3: The Voice of English Liberalism

Selections from The Economist: “Out with the long,” “Plus ça change? Not quite”

Optional reading: other essays from The Economist’s Johnson column

#### Week 4: New Journalism 

Joan Didion, “In Bed” and “Why I Write”

Optional reading: George Orwell, “Why I Write”

#### Week 5: Stream of Consciousness

Virginia Woolf, “Street Haunting” 

Optional reading: Virginia Woolf, “The Death of The Moth”

---

Each class lasts two hours, with a 10-minute break at the top of the hour. In class, the teacher will perform a close reading of that week’s texts, pulling out key words and phrases, and reviewing the answers to the comprehension questions. Students are invited to collaborate in the close-reading process and encouraged to raise their hands to ask questions at any time. Fifteen minutes are reserved for further questions at the end of class. 

Students should come prepared to class each week, having read and annotated the materials, and answered the comprehension questions. 

---

About the Teacher

BA in English from University of Cambridge (2009)

MA in East Asian Studies from Harvard University (2014)

MA in Creative Writing from the University of East Anglia (2023)

Grace Jackson is a writer, translator and educator based in the UK. A fluent Mandarin speaker, Grace has more than a decade of experience engaging with the Greater China region across the fields of education and the arts. She regularly designs and leads study abroad programs in China for secondary-aged students (past programs include studying history in Beijing, technology in Shenzhen and martial arts and Buddhism in Yunnan). Grace holds MA in East Asian Studies from Harvard University, where she was a Frank Knox Fellow, and a BA in English from the University of Cambridge, where she was awarded the Rylands Prize for best performance. She learned Mandarin in Beijing at 北语 and Taipei at the 国际华语研习所. Most recently, Grace graduated from the University of East Anglia with an MA in creative writing (non-fiction and biography). She is currently writing a non-fiction book about a nineteenth-century Scottish photographer’s travels in East Asia.

**Comment by brucexu-eth** [comment]
下一期写作主题的再用吧。

**Comment by wodeche** [comment]
这个公众号链接似乎过期了，需要中文互联网拯救计划！

**Comment by luffythink** [comment]
可以转到 Discussions 。
